using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Plugins;
using System.Drawing;
using System.Threading.Tasks;
using Water4ENBwatercolor.Settings;


namespace Water4ENBwatercolor
{

    public class Program
    {
        private static Lazy<Settings.Settings> _settings = null!;

        // ENB colors
        private static readonly Color ENBSunrise = Color.FromArgb(137, 160, 171);
        private static readonly Color ENBDay = Color.FromArgb(175, 216, 237);
        private static readonly Color ENBSunset = Color.FromArgb(105, 142, 154);
        private static readonly Color ENBNight = Color.FromArgb(31, 63, 75);

        // CS colors 
        private static readonly Color CSSunrise = Color.FromArgb(154, 154, 154);
        private static readonly Color CSDay = Color.FromArgb(210, 210, 210);
        private static readonly Color CSSunset = Color.FromArgb(138, 138, 138);
        private static readonly Color CSNight = Color.FromArgb(60, 60, 60);


        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "WaterColorPatcher.esp")
                .Run(args);
        }


        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {

            Color targetSunrise, targetDay, targetSunset, targetNight;
            if (_settings.Value.ENB)
            {
                targetSunrise = ENBSunrise;
                targetDay = ENBDay;
                targetSunset = ENBSunset;
                targetNight = ENBNight;
            }
            else
            {
                targetSunrise = CSSunrise;
                targetDay = CSDay;
                targetSunset = CSSunset;
                targetNight = CSNight;
            }

            int patchedCount = 0;

            foreach (var weatherGetter in state.LoadOrder.PriorityOrder.Weather().WinningOverrides())
            {
                var weather = state.PatchMod.Weathers.GetOrAddAsOverride(weatherGetter);
                weather.WaterMultiplierColor.Sunrise = targetSunrise;
                weather.WaterMultiplierColor.Day = targetDay;
                weather.WaterMultiplierColor.Sunset = targetSunset;
                weather.WaterMultiplierColor.Night = targetNight;

                patchedCount++;
            }

            System.Console.WriteLine($"Successfully patched {patchedCount} records with NaturalShadesOfSkyrim {_settings.Value.NaturalShadesOfSkyrim}.");
        }
    }
}